### Using Numpy to Create self attention

 Think of Self-Attention Like a Classroom Discussion
Imagine you are in a classroom discussing the sentence:

 **"The cat sat on the mat."**

You are the teacher, and you want to understand what each word in the sentence means in context by looking at all the other words.

 1: Understanding the Need for Attention
Each word in a sentence has a meaning, but its meaning depends on other words too.

Example:

The word "sat" means "to be in a sitting position."
But who is sitting? ("cat" is the subject).
Where? ("on the mat" tells us the location)

Instead of looking at words one by one, self-attention allows each word to "ask" other words for relevant information.

Step 2: Assigning Roles – Queries, Keys, and Values
To help each word decide what to focus on, we give each word three roles:

1. Query (Q) – The Question:

Each word "asks" about the meaning of the sentence from its perspective.
Example: "What is important for me to understand?"

2. Key (K) – The Information Holder:

Each word "offers" its meaning to others.
Example: "This is what I mean, take it if needed."

3. Value (V) – The Final Meaning:

Each word carries useful information that will be passed to others.

Think of this like students asking and answering questions in a classroom.

If you are the student (Query), you ask important questions (Q).
The other students (Keys) provide answers (K).
You collect and process those answers (V) to understand better.


Step 3: Scoring the Importance of Words
Now, each word "talks" to every other word and decides how important they are.

How? By comparing Queries (Q) and Keys (K)!

If a word’s Query (Q) matches well with another word’s Key (K), that means it’s important.
The higher the match, the more attention it gets!

 Step 4: Making the Attention Weights
Now that we have scores, we want to convert them into a proper weight (like a probability).

How? By applying softmax():

It makes the most important words stand out (high scores become bigger, low scores become smaller).
The total attention across all words sums to 1 (100%).

Step 5: Updating the Meaning Using Values (V)
Each word now mixes information from other words using the attention weights.

Each word’s final meaning is a blend of the words it pays attention to!

Example:

"sat" borrows information from "cat" and "on" (because they got high attention scores).
This helps "sat" understand that it refers to the cat sitting on something.

```
Q = X @ W_Q
K = X @ W_K
V = X @ W_V
```
`Attention_Scores = Q @ K.T
`

`Scaled_Scores = Attention_Scores / sqrt(d_k)
`

`Attention_Weights = softmax(Scaled_Scores)
`

`Output = Attention_Weights @ V
`

```
Self_Attention(Q, K, V) = softmax((Q @ K.T) / sqrt(d_k)) @ V

```

In [ ]:
import numpy as np

In [ ]:
# Define the input(Word embeddings)
x = np.array([[1, 0, 1],  # Word 1
    [0, 1, 1],  # Word 2
    [1, 1, 0]   # Word 3
])
print("Input word embeddings:", x)


Input word embeddings: [[1 0 1]
 [0 1 1]
 [1 1 0]]


In [ ]:
# Initialize Query(Q), Key(K), and Value(V) matrices using random numbers
q = np.random.rand(3, 3)
k = np.random.rand(3, 3)
v = np.random.rand(3, 3)

In [ ]:
print(q)

[[0.02982655 0.86754356 0.32277036]
 [0.67090353 0.28066548 0.02169685]
 [0.99935554 0.07557419 0.15867828]]


In [ ]:
print(q[0])
print(q[1])
print(q[2])

[0.02982655 0.86754356 0.32277036]
[0.67090353 0.28066548 0.02169685]
[0.99935554 0.07557419 0.15867828]


In [ ]:
print("row:",q.shape[0])

row: 3


In [ ]:
print("col:",q.shape[1])

col: 3


In [ ]:
# Compute q, k  and v
# Using dot product # (3x3) @ (3x3) --> 3
q_x = np.dot(x, q)
k_x = np.dot(x, k)
v_x = np.dot(x, v)

In [ ]:
print("Query:", q_x, "\n")
print("Key:", k_x, "\n")
print("Value:", v_x)

Query: [[1.02918209 0.94311775 0.48144864]
 [1.67025907 0.35623968 0.18037514]
 [0.70073007 1.14820905 0.34446721]] 

Key: [[0.88059947 0.96738799 0.82429994]
 [0.55447921 1.09563113 0.14715601]
 [0.96527645 1.57565102 0.70314209]] 

Value: [[1.26402321 1.5142024  1.32318979]
 [1.48882578 1.90282565 1.06119132]
 [1.32802383 1.49405674 1.10095084]]


In [ ]:
# Compute attention scores,dot T transpose
# Using dot product # (3x3) @ (3x3) --> 3
attention_scores = np.dot(q_x, k_x.T)

In [ ]:
print(attention_scores)

[[2.21551608 1.6748173  2.81799649]
 [1.96413445 1.34297449 2.3004005 ]
 [2.01177048 1.69724425 2.72778439]]


In [ ]:
# Apply softmax function
def softmax(x):
    return np.exp(x)/ np.sum(np.exp(x), axis = 1, keepdims = True)

In [ ]:
# Lets apply the softmax to get attention weights
attention_weights = softmax(attention_scores)

In [ ]:
attention_weights

array([[0.29334243, 0.17082538, 0.53583219],
       [0.34047976, 0.18294686, 0.47657339],
       [0.2648028 , 0.19334172, 0.54185548]])

In [ ]:
# Compute the final output (weighted sum of Values)
output = attention_weights @ v_x # (3x3) @ (3x3) -> (3x3)

print("Final Output After Self-Attention:\n\n", output)

Final Output After Self-Attention:

 [[1.33671879 1.56979442 1.15935102]
 [1.33565113 1.57569892 1.16934482]
 [1.34216601 1.57842345 1.15211316]]


### Using Pytorch to Create self attention

In [ ]:
import torch
import torch.nn as nn
import pandas as pd
import torch.nn.functional as F

In [ ]:
word = "I am a machine learning engineer"

# lets define word vocab
word_vocab = dict(enumerate(word.split()))

In [ ]:
word_vocab

{0: 'I', 1: 'am', 2: 'a', 3: 'machine', 4: 'learning', 5: 'engineer'}

In [ ]:
def reverse_dict(input_dict):
  return {value: key for key, value in input_dict.items()}

In [ ]:
vocab = reverse_dict(word_vocab)

In [ ]:
vocab

{'I': 0, 'am': 1, 'a': 2, 'machine': 3, 'learning': 4, 'engineer': 5}

In [ ]:
vocab_size = len(vocab)
# define embedding dimension
embedding_dim = 4

In [ ]:
# Create  an embedding layer
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

In [ ]:
# Convert sentence into token indices
token_indices = [vocab[word] for word in word.split()]
input_indices = torch.tensor(token_indices)

In [ ]:
# Get word embeddings
X = embedding_layer(input_indices)

In [ ]:
X.shape
#(num_words, embedding_dim)

torch.Size([6, 4])

In [ ]:
print(X)

tensor([[-0.1552,  1.0317,  1.5787, -1.3859],
        [-0.0997,  0.3827, -0.5121, -0.7133],
        [-0.8429, -0.0120, -1.1839, -1.6159],
        [ 0.3314,  1.6603, -0.1966, -0.3770],
        [ 1.4558,  2.6057, -0.7224, -1.8245],
        [-0.9696, -1.8205,  0.2053, -0.0396]], grad_fn=<EmbeddingBackward0>)


In [ ]:
# Lets compute for Q,K and V

# Define trainable weights matrices (embedding_dim, embedding_dim)

W_Q = torch.randn(embedding_dim, embedding_dim)
W_K = torch.randn(embedding_dim, embedding_dim)
W_V = torch.randn(embedding_dim, embedding_dim)

In [ ]:
# Compute Q, K, V
Q = X @ W_Q  # (6,4) @ (4,4) -> (6,4)
K = X @ W_K  # (6,4) @ (4,4) -> (6,4)
V = X @ W_V  # (6,4) @ (4,4) -> (6,4)

In [ ]:
print("\nQuery (Q):\n", Q)
print("\nKey (K):\n", K)
print("\nValue (V):\n", V)


Query (Q):
 tensor([[ 0.8388, -0.4577, -1.4179, -3.4429],
        [ 0.3344,  1.4597, -0.6583, -0.8520],
        [ 2.3609,  3.7756, -1.6642, -1.0781],
        [-2.0661,  0.4086, -0.6198, -1.9695],
        [-2.3459,  1.7674, -0.8779, -3.9946],
        [ 3.2354,  0.4677, -0.1180,  1.6178]], grad_fn=<MmBackward0>)

Key (K):
 tensor([[-0.0987, -4.3516, -2.8646, -5.3264],
        [ 0.2254, -0.0270,  0.9004,  1.1313],
        [-0.6867,  1.9948,  2.4314,  3.6758],
        [ 1.5325, -2.9488,  0.1252, -1.2027],
        [ 3.1263, -5.1399,  0.2864, -0.8180],
        [-2.2940,  3.6204,  0.1796,  1.5265]], grad_fn=<MmBackward0>)

Value (V):
 tensor([[ 1.2768, -3.3923, -3.0889,  0.2982],
        [ 1.1344,  0.6626, -0.1441, -1.0227],
        [ 1.0953,  1.1428, -0.0482, -1.3260],
        [ 2.7697,  1.3958, -0.5323, -3.0442],
        [ 5.5748,  0.8515, -1.4998, -3.0465],
        [-3.0427, -1.5246,  0.2519,  2.7946]], grad_fn=<MmBackward0>)


In [ ]:
# Lets compute Attention Scores (dot product of Q and K^T)
attention_scores = Q @ K.T

print(attention_scores)

tensor([[ 24.3090,  -4.9704, -17.5920,   6.5986,   7.3851,  -9.0916],
        [  0.0386,  -1.5207,  -2.0501,  -2.8497,  -5.9490,   3.0988],
        [ -6.1531,  -2.2881,  -2.0991,  -6.4270, -11.6200,   6.3085],
        [ 10.6912,  -3.2630,  -6.5124,  -2.0802,  -7.1261,   3.1014],
        [ 16.3321,  -5.8863, -11.6813,  -4.1122, -13.4019,   5.5247],
        [-10.6333,   2.4407,   4.3708,   1.6188,   6.3541,  -3.2807]],
       grad_fn=<MmBackward0>)


In [ ]:
# Lets scale the scores
scaled_scores = attention_scores / (embedding_dim ** 0.5)
#scaled_scores = attention_scores / torch.sqrt(torch.tensor(embedding_dim, dtype=torch.float32))
scaled_scores

tensor([[12.1545, -2.4852, -8.7960,  3.2993,  3.6925, -4.5458],
        [ 0.0193, -0.7604, -1.0251, -1.4248, -2.9745,  1.5494],
        [-3.0766, -1.1440, -1.0496, -3.2135, -5.8100,  3.1542],
        [ 5.3456, -1.6315, -3.2562, -1.0401, -3.5630,  1.5507],
        [ 8.1661, -2.9431, -5.8407, -2.0561, -6.7010,  2.7623],
        [-5.3166,  1.2203,  2.1854,  0.8094,  3.1770, -1.6404]],
       grad_fn=<DivBackward0>)

In [ ]:
# Apply softmax
attention_weights = F.softmax(scaled_scores, dim=-1)
print(attention_weights)

tensor([[9.9965e-01, 4.3843e-07, 7.9644e-10, 1.4258e-04, 2.1128e-04, 5.5847e-08],
        [1.4891e-01, 6.8287e-02, 5.2405e-02, 3.5136e-02, 7.4601e-03, 6.8780e-01],
        [1.9062e-03, 1.3166e-02, 1.4471e-02, 1.6622e-03, 1.2390e-04, 9.6867e-01],
        [9.7521e-01, 9.0988e-04, 1.7922e-04, 1.6437e-03, 1.3186e-04, 2.1928e-02],
        [9.9547e-01, 1.4906e-05, 8.2222e-07, 3.6190e-05, 3.4783e-07, 4.4794e-03],
        [1.2684e-04, 8.7545e-02, 2.2980e-01, 5.8045e-02, 6.1947e-01, 5.0101e-03]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
# Compute final output
output = attention_weights @ V
print(output)

tensor([[ 1.2780, -3.3907, -3.0882,  0.2970],
        [-1.6289, -1.3933, -0.3290,  1.6975],
        [-2.9089, -1.4556,  0.2345,  2.6695],
        [ 1.1850, -3.3384, -3.0080,  0.3455],
        [ 1.2575, -3.3837, -3.0738,  0.3092],
        [ 3.9501,  0.9211, -0.9828, -2.4441]], grad_fn=<MmBackward0>)
